language: node_js
node_js:
  - "10.0.0"

before_install:
  - npm install -g typescript

jobs:
  include:
    - stage: npm release
      node_js: "10.0.0"
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: "support@snax.one"
        api_key: "$NPM_API_KEY"
        on:
          branch: master
